remote_theme: glasnt/myrtle@latest
base_url: /blog
BASE_PATH: /blog
media: /blog/assets/media

permalink: "/:title"
plugins: 
 - jekyll-redirect-from
 - jekyll-remote-theme

header-img: "../img/header_image.jpg"
base_author: "Katie McLaughlin"
cardfolder: "/assets/cards"

future: true
timezone: "Australia/Sydney"

google_analytics: "G-265B4NHGG0"

rss_path: "feed.xml"
categories_path: "categories.html"
archive_path: "archive.html"

title: "musings"
