remote_theme: glasnt/myrtle@thinkspace
repository: glasnt/blog

description       : "in which glasnt has thoughts"     
baseurl           : "/blog"

title_left         : "glasnt.com"
url                : "https://glasnt.com"
google_analytics   : G-265B4NHGG0
twitter_username   : "glasnt"     
postshare_enabled  : true

permalink          : /:title/
markdown           : kramdown
highlighter        : rouge

# special settings for blog
media: /blog/assets/media
cardfolder: /assets/cards

navbar:
  - slug : /
    title: home
  - slug : /blog/about/
    title: about
  - slug: /talks/
    title: talks
  - slug: /writing/
    title: writing
  - slug: /blog/
    title: blog
  - slug: /blog/now/
    title: now
  - slug: /blog/archive/
    title: archive
