remote_theme: glasnt/myrtle
base_url: /blog
BASE_PATH: /blog

permalink: "/:title" #:categories/:year/:month/:day/:title.html"

header-img: "../img/header_image.jpg"
base_author: "Katie McLaughlin"

future: true
timezone: "Australia/Sydney"

google_analytics: "UA-18568982-1"

rss_path: "feed.xml"
categories_path: "categories.html"
archive_path: "archive.html"

title: "musings"
